### ISSUE TITLE
Some issues with the CLI

### ISSUE THREAD

**Issue by nightblade9** [MikeSchulze/gdUnit3#219]
**The used Godot version:** 3.4.2

**OS including version:** Windows, Linux

**Describe the bug**
The CLI instructions on the wiki appear wrong. (The ones in the CLI program itself, also appear wrong.) They all refer a command "testrun" which doesn't seem to exist; to run all the tests in `tests`, I have to use this command: `<godot executable path>  -s addons/gdUnit3/bin/GdUnitCmdTool.gd --add tests`

It would be great if you could update the wiki steps appropriately (maybe I'm doing something wrong?) - I was looking for instructions to run tests via GitHub Actions.

Also, is it possible that `GdUnitCmdTool.gd` can return a non-zero code if it executes and any tests fail, or any other errors appear in tests?

**Comment by MikeSchulze** [comment]
Hi @nightblade9 

There exists a script, see at  https://github.com/MikeSchulze/gdUnit3/blob/master/runtest.sh for mac and a https://github.com/MikeSchulze/gdUnit3/blob/master/runtest.cmd for windows.

I will check later to day if this scripts included in the plugin installed over the asset lib.
From repository looks like it is not placed inside the plugin ;(
As workaround you can copy manually from described resources below.

Can you send me a link to the wrong Wiki entry please, i will fix it.

I have setup my GitHub Actions by:
```
name: CI GdUnit3 on Godot 3.4.x
on: [push, workflow_dispatch]

jobs:
  testing:
    strategy:
      matrix:
        godot: [3.4]

    name: CI Godot ${{ matrix.godot }}
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:${{ matrix.godot }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: 'recursive'

      - name: Setup
        shell: bash
        run: echo "GODOT_BIN=/usr/local/bin/godot" >> $GITHUB_ENV

      - name: Run Selftes
        timeout-minutes: 5
        shell: bash
        run: ./runtest.sh --selftest

      - name: Collect Test Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Report_${{ matrix.godot }}
          path: reports/**
```

The script returns already the exit code defined as
	const RETURN_SUCCESS  =   0
	const RETURN_ERROR    = 100
	const RETURN_WARNING  = 101
