### ISSUE TITLE
Add Gitlab CI example code to docs

### ISSUE THREAD

**Issue by mzoeller** [MikeSchulze/gdUnit3#247]
### Description
I thought I'd share my gitlab-ci.yml here. Maybe adding this code to the docs will help others to set up gdunit3 with their pipeline.
This uses https://github.com/abarichello/godot-ci Docker image. It will automatically run all tests inside ./test and also parse the results.xml file adding the report to the pipeline's test report page in GitLab.

Example .gitlab-ci.yml file:
```
image: barichello/godot-ci:3.4.4

cache:
  key: import-assets
  paths:
    - .import/

stages:
  - export
  - tests
  - deploy

variables:
  EXPORT_NAME: $CI_PROJECT_NAME
  GIT_SUBMODULE_STRATEGY: recursive

linux:
  stage: export
  script:
    - mkdir -v -p build/linux
    - godot -v --export "Linux/X11" build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux

gdunit3:
  stage: tests
  dependencies:
    - linux
  script:
    - export GODOT_BIN=/usr/local/bin/godot
    - ./runtest.sh -a ./test || if [ $? -eq 101 ]; then echo "warnings"; elif [ $? -eq 0 ]; then echo "success"; else exit 1; fi
  artifacts:
    when: always
    reports:
      junit: ./reports/report_1/results.xml
```

### Acceptance criteria
-
